services:
  keycloak:
    build: ./keycloak
    container_name: keycloak
    restart: unless-stopped
    expose:
      - 8080
      - 8443
    environment:
      VIRTUAL_HOST: id.kwagga.ru
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: id.kwagga.ru
    networks:
      - dev

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kwagga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rustam2003
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - dev
    volumes:
      - database:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    volumes:
      - minio_storage:/data
    environment:
      VIRTUAL_HOST: minio.kwagga.ru
      VIRTUAL_PORT: 9001
      LETSENCRYPT_HOST: minio.kwagga.ru
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Rustam2003
    expose:
      - 9000
      - 9001
    networks:
      - dev
    command: server --console-address ":9001" /data

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis
    restart: unless-stopped
    command: >
      sh -c '
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redis:/resources
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/usr/local/etc/redis/users.acl
    networks:
      - dev

volumes:
  minio_storage:
  database:
  redis:

networks:
  dev:
    external: true
